-- ============================================================================
-- WEEK 3: TOPIC 3 — Conformed Dimensions with Surrogate Keys & -1 Fallbacks
-- Description:
-- Transforming your existing 3NF tables into Kimball Conformed Dimensions:
--   - customer.customers + customer.addresses ──► dwh.dim_customer
--   - catalog.products + catalog.categories   ──► dwh.dim_product
--   - logistics.warehouses                    ──► dwh.dim_warehouse
--
-- Key Dimensional Principles Illustrated:
-- 1. Denormalization: Flattening category into dim_product; flattening primary
--    address into dim_customer (eliminates costly multi-hop joins).
-- 2. Surrogate Primary Keys: Generated BIGINT identity keys decoupled from source UUIDs.
-- 3. Natural / Business Keys: UUIDs and operational codes retained for auditability.
-- 4. Mandatory -1 Record: Fallback row preventing pipeline failures on missing data.
-- 5. Address Window Function Deduplication: Selecting the single primary address.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS dwh;

-- ----------------------------------------------------------------------------
-- 1. DIM_CUSTOMER
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS dwh.dim_customer CASCADE;

CREATE TABLE dwh.dim_customer (
    customer_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID NOT NULL UNIQUE,          -- Operational UUID from customer.customers
    customer_code VARCHAR(50) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(60) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(50),
    customer_status VARCHAR(50) NOT NULL,
    signup_date DATE,
    address_line_1 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(30) NOT NULL,
    country VARCHAR(100) NOT NULL,
    dw_created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    dw_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed -1 Unknown Customer Record
INSERT INTO dwh.dim_customer (
    customer_sk, customer_id, customer_code, full_name, first_name, last_name,
    email, phone, customer_status, signup_date, address_line_1, city, state, postal_code, country
) VALUES (
    -1, '00000000-0000-0000-0000-000000000000', 'UNKNOWN', 'Unknown Customer', 'Unknown', 'Customer',
    'unknown@example.com', 'N/A', 'Active', '1900-01-01', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A'
);

-- ----------------------------------------------------------------------------
-- 2. DIM_PRODUCT (Denormalizing Category into Product)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS dwh.dim_product CASCADE;

CREATE TABLE dwh.dim_product (
    product_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id UUID NOT NULL UNIQUE,           -- Operational UUID from catalog.products
    sku VARCHAR(50) NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    category_name VARCHAR(100) NOT NULL,
    cost_price NUMERIC(10, 2) NOT NULL,
    product_status VARCHAR(30) NOT NULL,
    launch_date DATE,
    dw_created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    dw_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed -1 Unknown Product Record
INSERT INTO dwh.dim_product (
    product_sk, product_id, sku, product_name, brand,
    category_name, cost_price, product_status, launch_date
) VALUES (
    -1, '00000000-0000-0000-0000-000000000000', 'UNKNOWN', 'Unknown Product', 'Unknown Brand',
    'Uncategorized', 0.00, 'Inactive', '1900-01-01'
);

-- ----------------------------------------------------------------------------
-- 3. DIM_WAREHOUSE (From logistics.warehouses)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS dwh.dim_warehouse CASCADE;

CREATE TABLE dwh.dim_warehouse (
    warehouse_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id UUID NOT NULL UNIQUE,
    warehouse_code VARCHAR(30) NOT NULL,
    warehouse_name VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    capacity INT NOT NULL,
    dw_created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed -1 Unknown Warehouse Record
INSERT INTO dwh.dim_warehouse (
    warehouse_sk, warehouse_id, warehouse_code, warehouse_name, city, state, country, capacity
) VALUES (
    -1, '00000000-0000-0000-0000-000000000000', 'UNKNOWN', 'Unknown Warehouse', 'N/A', 'N/A', 'N/A', 0
);

-- ----------------------------------------------------------------------------
-- 4. ELT TRANSFORMATION PIPELINES (Populate Dimensions from Live 3NF Tables)
-- ----------------------------------------------------------------------------

-- A) Load dim_customer with Window Function Address Deduplication
WITH ranked_addresses AS (
    SELECT 
        customer_id,
        address_line_1,
        city,
        state,
        postal_code,
        country,
        ROW_NUMBER() OVER (
            PARTITION BY customer_id 
            ORDER BY is_default DESC, created_at DESC
        ) AS addr_rank
    FROM customer.addresses
)
INSERT INTO dwh.dim_customer (
    customer_id, customer_code, full_name, first_name, last_name,
    email, phone, customer_status, signup_date,
    address_line_1, city, state, postal_code, country
)
SELECT 
    c.customer_id,
    c.customer_code,
    c.first_name || ' ' || c.last_name AS full_name,
    c.first_name,
    c.last_name,
    c.email,
    COALESCE(c.phone, 'N/A'),
    c.customer_status,
    c.signup_date::DATE,
    COALESCE(a.address_line_1, 'No Address Provided'),
    COALESCE(a.city, 'Unknown City'),
    COALESCE(a.state, 'Unknown State'),
    COALESCE(a.postal_code, 'N/A'),
    COALESCE(a.country, c.country, 'Unknown Country')
FROM customer.customers c
LEFT JOIN ranked_addresses a 
    ON c.customer_id = a.customer_id AND a.addr_rank = 1
ON CONFLICT (customer_id) 
DO UPDATE SET
    full_name = EXCLUDED.full_name,
    email = EXCLUDED.email,
    customer_status = EXCLUDED.customer_status,
    address_line_1 = EXCLUDED.address_line_1,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    postal_code = EXCLUDED.postal_code,
    country = EXCLUDED.country,
    dw_updated_at = CURRENT_TIMESTAMP;

-- B) Load dim_product (Denormalizing Categories)
INSERT INTO dwh.dim_product (
    product_id, sku, product_name, brand,
    category_name, cost_price, product_status, launch_date
)
SELECT 
    p.product_id,
    p.sku,
    p.product_name,
    p.brand,
    COALESCE(cat.category_name, 'Uncategorized'),
    p.cost_price,
    p.status AS product_status,
    p.launch_date
FROM catalog.products p
LEFT JOIN catalog.categories cat ON p.category_id = cat.category_id
ON CONFLICT (product_id)
DO UPDATE SET
    sku = EXCLUDED.sku,
    product_name = EXCLUDED.product_name,
    brand = EXCLUDED.brand,
    category_name = EXCLUDED.category_name,
    cost_price = EXCLUDED.cost_price,
    product_status = EXCLUDED.product_status,
    launch_date = EXCLUDED.launch_date,
    dw_updated_at = CURRENT_TIMESTAMP;

-- C) Load dim_warehouse
INSERT INTO dwh.dim_warehouse (
    warehouse_id, warehouse_code, warehouse_name, city, state, country, capacity
)
SELECT 
    warehouse_id,
    warehouse_code,
    warehouse_name,
    city,
    state,
    country,
    capacity
FROM logistics.warehouses
ON CONFLICT (warehouse_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- VERIFICATION
-- ----------------------------------------------------------------------------
SELECT count(*) AS total_dim_customers FROM dwh.dim_customer;
SELECT count(*) AS total_dim_products FROM dwh.dim_product;
SELECT count(*) AS total_dim_warehouses FROM dwh.dim_warehouse;
