-- ============================================================================
-- WEEK 3: TOPIC 6 — Fact Table DDL & Grain Contract
-- Description:
-- Central Sales Fact Table mapped directly to your database's order_items and orders.
--
-- GRAIN CONTRACT:
-- "One row represents one line item within an order placed by a customer."
--
-- Core Design Elements:
-- 1. Surrogate Foreign Keys: Integer / Bigint foreign keys referencing conformed dims.
-- 2. Degenerate Dimensions: order_number, order_item_id, order_status, currency.
-- 3. Additive Measures: quantity, gross_amount, discount, net_sales, cost, gross_margin.
-- 4. Allocated Header Measures: Proportionately allocated order taxes and shipping fees.
-- 5. Grain Constraint: Unique constraint on order_item_id.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS dwh;

DROP TABLE IF EXISTS dwh.fact_sales_order_lines CASCADE;

CREATE TABLE dwh.fact_sales_order_lines (
    -- Surrogate Primary Key for the Fact Record
    sales_order_line_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Dimension Surrogate Foreign Keys (Integer SKs, never NULL, default -1)
    order_date_fk INT NOT NULL REFERENCES dwh.dim_date(date_key),
    customer_fk BIGINT NOT NULL REFERENCES dwh.dim_customer(customer_sk),
    product_fk BIGINT NOT NULL REFERENCES dwh.dim_product(product_sk),
    -- Degenerate Dimensions (Stored directly on fact)
    order_number VARCHAR(50) NOT NULL,
    order_item_id UUID NOT NULL UNIQUE,       -- Operational Natural ID for Line
    order_status VARCHAR(30) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    -- Additive Measures
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(10, 2) NOT NULL,
    line_gross_amount NUMERIC(10, 2) NOT NULL,
    line_discount_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    net_sales_amount NUMERIC(10, 2) NOT NULL,
    cost_amount NUMERIC(10, 2) NOT NULL,
    gross_margin_amount NUMERIC(10, 2) NOT NULL,
    -- Allocated Header Measures (Tax & Shipping prorated across order lines)
    allocated_tax_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    allocated_shipping_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    -- Audit Metadata
    dw_inserted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Fast Star Join Indexes
CREATE INDEX idx_fact_sales_order_date ON dwh.fact_sales_order_lines(order_date_fk);
CREATE INDEX idx_fact_sales_customer   ON dwh.fact_sales_order_lines(customer_fk);
CREATE INDEX idx_fact_sales_product    ON dwh.fact_sales_order_lines(product_fk);
CREATE INDEX idx_fact_sales_order_num  ON dwh.fact_sales_order_lines(order_number);

COMMENT ON TABLE dwh.fact_sales_order_lines IS 'Grain: One row per individual item line within an order from orders.order_items.';
