-- ============================================================================
-- WEEK 3: TOPIC 9 — Accumulating Snapshot Fact Table Pattern
-- Description:
-- Kimball Accumulating Snapshot Fact table tracking the order fulfillment lifecycle:
-- (Order Placed -> Order Shipped -> Order Delivered) across orders and shipments.
--
-- Core Characteristics:
-- - Grain: One row per order lifecycle entity.
-- - Updated in place as fulfillment milestones occur.
-- - Role-playing date foreign keys for each lifecycle milestone.
-- - Lag and duration metrics (days to ship, days in transit, total turnaround).
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS dwh;

DROP TABLE IF EXISTS dwh.fact_order_fulfillment_accumulating CASCADE;

CREATE TABLE dwh.fact_order_fulfillment_accumulating (
    fulfillment_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID NOT NULL UNIQUE,
    order_number VARCHAR(50) NOT NULL,
    carrier VARCHAR(50),
    tracking_number VARCHAR(50),
    -- Dimension Foreign Keys
    customer_fk BIGINT NOT NULL REFERENCES dwh.dim_customer(customer_sk),
    warehouse_fk BIGINT NOT NULL REFERENCES dwh.dim_warehouse(warehouse_sk),
    -- Milestone Date Role Foreign Keys (Default -1 Unknown until milestone reached)
    order_date_fk INT NOT NULL REFERENCES dwh.dim_date(date_key),
    shipped_date_fk INT NOT NULL REFERENCES dwh.dim_date(date_key) DEFAULT -1,
    delivered_date_fk INT NOT NULL REFERENCES dwh.dim_date(date_key) DEFAULT -1,
    -- Business Lag & Duration Measures (Days)
    days_to_ship NUMERIC(8, 2),
    days_in_transit NUMERIC(8, 2),
    total_delivery_days NUMERIC(8, 2),
    -- Financial Measures at Order Grain
    total_amount NUMERIC(10, 2) NOT NULL,
    shipping_amount NUMERIC(10, 2) NOT NULL,
    -- Flags
    is_delivered BOOLEAN NOT NULL DEFAULT FALSE,
    is_delayed BOOLEAN NOT NULL DEFAULT FALSE,
    dw_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------------------------
-- ELT LOAD: Populate Accumulating Snapshot from orders.orders & logistics.shipments
-- ----------------------------------------------------------------------------
INSERT INTO dwh.fact_order_fulfillment_accumulating (
    order_id,
    order_number,
    carrier,
    tracking_number,
    customer_fk,
    warehouse_fk,
    order_date_fk,
    shipped_date_fk,
    delivered_date_fk,
    days_to_ship,
    days_in_transit,
    total_delivery_days,
    total_amount,
    shipping_amount,
    is_delivered,
    is_delayed
)
SELECT 
    o.order_id,
    o.order_number,
    COALESCE(s.carrier, 'Unassigned') AS carrier,
    COALESCE(s.tracking_number, 'Pending') AS tracking_number,
    COALESCE(c.customer_sk, -1) AS customer_fk,
    COALESCE(w.warehouse_sk, -1) AS warehouse_fk,
    -- Milestone 1: Order Date Key
    COALESCE(TO_CHAR(o.order_timestamp, 'YYYYMMDD')::INT, -1) AS order_date_fk,
    -- Milestone 2: Shipped Date Key
    COALESCE(TO_CHAR(s.shipped_at, 'YYYYMMDD')::INT, -1) AS shipped_date_fk,
    -- Milestone 3: Delivered Date Key
    COALESCE(TO_CHAR(s.delivered_at, 'YYYYMMDD')::INT, -1) AS delivered_date_fk,
    -- Lag Metrics
    CASE 
        WHEN s.shipped_at IS NOT NULL THEN
            ROUND(EXTRACT(EPOCH FROM (s.shipped_at - o.order_timestamp)) / 86400.0, 2)
        ELSE NULL 
    END AS days_to_ship,
    CASE 
        WHEN s.delivered_at IS NOT NULL AND s.shipped_at IS NOT NULL THEN
            ROUND(EXTRACT(EPOCH FROM (s.delivered_at - s.shipped_at)) / 86400.0, 2)
        ELSE NULL 
    END AS days_in_transit,
    CASE 
        WHEN s.delivered_at IS NOT NULL THEN
            ROUND(EXTRACT(EPOCH FROM (s.delivered_at - o.order_timestamp)) / 86400.0, 2)
        ELSE NULL 
    END AS total_delivery_days,
    o.total_amount,
    o.shipping_amount,
    CASE WHEN s.delivered_at IS NOT NULL THEN TRUE ELSE FALSE END AS is_delivered,
    CASE 
        WHEN s.delivered_at IS NOT NULL AND s.estimated_delivery_at IS NOT NULL 
             AND s.delivered_at > s.estimated_delivery_at THEN TRUE 
        ELSE FALSE 
    END AS is_delayed
FROM orders.orders o
LEFT JOIN logistics.shipments s ON o.order_id = s.order_id
LEFT JOIN dwh.dim_customer c ON o.customer_id = c.customer_id
LEFT JOIN dwh.dim_warehouse w ON s.warehouse_id = w.warehouse_id
ON CONFLICT (order_id)
DO UPDATE SET
    carrier = EXCLUDED.carrier,
    tracking_number = EXCLUDED.tracking_number,
    warehouse_fk = EXCLUDED.warehouse_fk,
    shipped_date_fk = EXCLUDED.shipped_date_fk,
    delivered_date_fk = EXCLUDED.delivered_date_fk,
    days_to_ship = EXCLUDED.days_to_ship,
    days_in_transit = EXCLUDED.days_in_transit,
    total_delivery_days = EXCLUDED.total_delivery_days,
    is_delivered = EXCLUDED.is_delivered,
    is_delayed = EXCLUDED.is_delayed,
    dw_updated_at = CURRENT_TIMESTAMP;

-- ----------------------------------------------------------------------------
-- VERIFICATION
-- ----------------------------------------------------------------------------
SELECT 
    count(*) AS total_fulfillment_orders,
    count(*) FILTER (WHERE is_delivered = TRUE) AS delivered_orders,
    count(*) FILTER (WHERE is_delayed = TRUE) AS delayed_orders,
    ROUND(AVG(days_to_ship), 2) AS avg_days_to_ship,
    ROUND(AVG(days_in_transit), 2) AS avg_days_in_transit,
    ROUND(AVG(total_delivery_days), 2) AS avg_total_delivery_days
FROM dwh.fact_order_fulfillment_accumulating;
